on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Query
        id: query
        uses: ./
        with:
          query: "SELECT 'This is query' AS out;"
          config: |
            user=${{ vars.TRINO_USERNAME }}
            server=https://starbursttelemetry-data-lake.trino.galaxy.starburst.io
          password: '${{ secrets.TRINO_PASSWORD }}'
      - name: Run Query File
        id: query-file
        uses: ./
        with:
          query-file: test/query.sql
          config: |
            user=${{ vars.TRINO_USERNAME }}
            server=https://starbursttelemetry-data-lake.trino.galaxy.starburst.io
          password: '${{ secrets.TRINO_PASSWORD }}'
      - name: Get outputs
        run: |
          echo "${{ steps.query.outputs.result }}"
          echo "${{ steps.query-file.outputs.result }}"